spring.application.name=wordlyai-backend
spring.profiles.default=dev
spring.config.import=optional:file:.env[.properties]

spring.jpa.open-in-view=false

app.jwt.secret=${JWT_SECRET}
app.jwt.expiration-seconds=${JWT_EXPIRATION_SECONDS:3600}
